# Generated by Django 3.2.8 on 2022-01-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('describe', models.CharField(max_length=300)),
                ('create_date', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categorytb',
            },
        ),
        migrations.CreateModel(
            name='AdportalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'adportal',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('subdate', models.CharField(max_length=30)),
                ('categorytb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adportal.addcategorymodel')),
            ],
            options={
                'db_table': 'subcategorytb',
            },
        ),
    ]
